"""Add users

Revision ID: f21007a41c85
Revises: 04d1be36273b
Create Date: 2023-10-16 15:21:15.176425

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f21007a41c85"
down_revision: Union[str, None] = "04d1be36273b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("crated_at", sa.DateTime(), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("contacts", sa.Column("users_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "contacts", "users", ["users_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "users_id")
    op.drop_table("users")
    # ### end Alembic commands ###
